spring:
  application:
    name: bookstore-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: 1234
