SELECT *
FROM PG_CATALOG.PG_TABLES
WHERE SCHEMANAME LIKE 'public';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('authors', 'books');

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('flyway_schema_history');
